### ISSUE TITLE
RaccoonWalletの育成アイデア・プライオリティ・ロードマップ的な何か

### ISSUE THREAD

**Issue by SasakiYuki** [SasakiYuki/RaccoonWallet#1]
# Rhimeさん提案
タヌキを育てるためのevernoteに思いつきで書いてたロードマップとアイデア一覧
ロードマップ的告知用にグラフィックも思いつきでぽいの作った。

---

## 直近で取り組みたいもの

![raccoonwallet_tablet](https://user-images.githubusercontent.com/34479640/40404131-2616515c-5e91-11e8-96d8-5a0add7140b1.jpg)

1. タブレット最適化
ソフトウェアがしっかりとしていれば、タブレットは簡易posとして充分機能するはず。
デザイン破綻がないようにチェック。

![raccoonwallet_qrlab_list](https://user-images.githubusercontent.com/34479640/40429932-ce3c0c9e-5ede-11e8-86e0-3388ef2cb9cf.jpg)

2. QRラボ｜売り物リスト
#226  
ここの議論などから。優先順位高め。

![raccoonwallet_pwa_ios2](https://user-images.githubusercontent.com/34479640/40482422-b6efd76c-5f8f-11e8-8484-df49976b29fb.jpg)

3. iOS PWA
りゅーたさん無双。

※追記5/28：**PWA 版**で完全に **Android と同じ機能を提供するのは無理な部分がある。**
カメラに関しては今後 iOS のバージョンが上がったときに解決する可能性はありますが、それも Apple 任せ。
PWA版でウォレットの機能提供できるようになったら、**一度そのPWA版をアプリ化してストアに申請してみる。** →今のコードをある程度流用してストアにアプリ化することはできるみたいなので、**それで申請して通れば iOS ネイティブで作りなおして更新する。**

## アイデア

![raccoonwallet_lightningpay2](https://user-images.githubusercontent.com/34479640/40404468-f461deb8-5e92-11e8-8f7f-ef9026128f67.jpg)

1. ライトニングペイ
連続的高速ペイモード
あらかじめモザイクの種類や金額を設定し、認証でモードを開始すると、カメラでQRを読みとった瞬間にtxを生成し、かつ任意でモードを終了するまで連続的にtxを生成できる。（ポポポポポポポポンンッ！！！！！
利用→特定モザイクを配りまくる時。

- ex1)有名人がファンにモザイクを配る。
- ex2)スタンプカードで、イベント時に条件クリアした際の受領印としてモザイクを使用する時
- 使用状況は多様にある

効用→ライトニングペイ使用料として0.5XEM程度のtxを、認証と同時にラクーンのマルチシグアドレス宛てに生成することで、マイクロペイメント的マネタイズができる可能性。巷ではマイクロペイメント、マイクロペイメントいうてるくせに、いまのところこのぐらいの超少額課金・超小規模サービスというのに出会ったことがないのはワシだけか。

![raccoonwallet_universal](https://user-images.githubusercontent.com/34479640/40404480-02d14a92-5e93-11e8-99f0-a2fbe4048eff.jpg)

2. ユニバーサルモード：視覚、聴覚、老眼配慮
→超簡略化、デカ文字化。（参考:添付図。
スマホの振動やサウンドもデザインする。
子供向けにも幅広い応用が可能。
あとマテリアルデザイン2.0の実装とデザインの練習にも最適かもしれない（笑

![ink-image_universal_raccoon](https://user-images.githubusercontent.com/34479640/40404528-42f7666a-5e93-11e8-8fa2-35c8bd58a396.png)

3. 英語対応
最初Soon枠に入れてたけど、ついさっき海外NEMberからリプライがあって「もしよかったらNEMフォーラムにポストを投稿して、コミュニティにトランスレーションしてくれる人がいないか聞いてみてもいいよ」というイケメンがいらしたので、現実味を帯びた。
https://twitter.com/aleix_mp/status/998859158404456453

また、仮想通貨に理解のある翻訳歴１５年の通訳の方も。
https://twitter.com/translatorinoue
https://twitter.com/CryptoRhizome/status/998859848228876294

どうやらフランクな英語にするには、日本人が硬くても自動翻訳でもいいから翻訳→ネイティブにフランクに翻訳してもらう　だと、言い回しも古くさくならずにいい、らしい。

### XEM決済系

1. あなたの個性を加速する：カスタム店舗

何かが速くなったことで、どこかがゆっくりになる

- 効率化・スピード→例：QRコード読み取り精度向上、ライトニングペイその他
- 情緒・スロー→何かが速くなったことで、どこかがゆっくりになる→端末を通したお客さんとの対話＝カスタム店舗と連動して生まれるエモーショナル。仮想通貨におけるリアルタイム物販の無機質さが改善され、よりエモくなる。タブレットと合わせると最高にエモい。アイデンティティ。

### カスタマイズ系
1. プロフィールイメージカスタマイズ
カスタム店舗のPersonal版。アドレス帳と共に。

### Soon

・アグリゲートトランザクションによる即時交換
A：SEND→◯ラクーン←B：SEND　で待機。確認後、エクスチェンジ↑↓

## 補：マネタイズのための概念定義

サービス受領の変革
1.0 買い切り
2.0 サブスクリプション
3.0 セッションペイ （そんな言葉はないけど）　←イマココ

マイクロペイメントによる１セッションごとの使用料支払い。
サブスクリプションの問題点は何か？→使わんときに払うカネは庶民にとってびた一文無いのである。

**Comment by SasakiYuki** [comment]
- 共創プラットフォーム
- 買う人も、売る人も #RaccoonWallet

**Comment by mizunashi** [comment]
もの凄く期待しています。
頑張ってください！

**Comment by Rhime-design** [comment]
うわ～！みなりんさ～ん！うれしすぎる！
コメント、サイトに乗っけてもいいですか！？（もっと別の形の文言のほうがよろしかったら、違う感じで褒めていただいても、、、ｗ

**Comment by mizunashi** [comment]
勿論大丈夫ですよ。そして、twitterでもガン押ししたいと思っています＾＾

**Comment by Rhime-design** [comment]
よっしゃ！(ง '-' )ง
（実はサイトの目立つところに、シンプルに一言みなりんさんのコメントを載せたいと思ってました。夢が叶ったぞ:raised_hands:）

心強い！ありがとうございます！

**Comment by SasakiYuki** [comment]
一定期間動いていないためリポジトリールールによりクローズします🤖
議論が必要になった際に再オープンしましょう🤖
