### ISSUE TITLE
QR読み込み時の不具合

### ISSUE THREAD

**Issue by SasakiYuki** [SasakiYuki/RaccoonWallet#18]
baneoさんより

小数点以下4桁以降が表示されていない
送金するとされているようなので表示のみされていないという一番やな状態　直す

またメッセージも無視されている模様なのでそちらも合わせて修正する

**Comment by SasakiYuki** [comment]
QR形式の羅列

そもそもQR形式にどんな種類が存在するか
https://github.com/SasakiYuki/RaccoonWallet/blob/3c2db2e9e2937239289a46855ae74881b55bf7f7/app/src/main/java/wacode/yamada/yuki/nempaymentapp/model/PaymentQREntity.kt

```
        val addr: String,
        val amount: Long,
        val msg: String,
        val name: String? = ""
```

上部三つがすでに入っている場合はダイレクトで決済確認画面へ飛ぶ
それ以外の場合はそれぞれの場所からスタートするのが親切そう

例えばaddressのみ入っているQRなら数字入力画面から
amountもすでに入っていればmsgを付けるかどうかから

nameは考慮しない（QRに含まれる場合表示だけはしてあげるが変更するUIはない）

**Comment by Soma-Kato** [comment]
Sasakiと議論したので、そのメモです

QRコードを読み込みの際の挙動変更
1. `ニュービーDialog`の廃止->QRコードから読み込んだので、アドレスは間違ってないと思われる
2. QRを読み込んだデータに`アドレス`が存在し、かつ`amount`が0になっている場合 -> `amountが0だけど大丈夫かを確認するDialog`を表示
yes -> message指定画面に遷移
no -> 金額指定画面に遷移
3. QRを読み込んだデータに`アドレス`が存在し、かつ`amount`が0以上になっている場合 -> `messageが空だけど大丈夫かを確認するDialog`を表示
yes -> 送金確認画面に遷移
no -> message種類指定画面に遷移
4. QRを読み込んだデータに`アドレス`が存在かつ`amount`が0以上かつ`message`が空じゃない場合 -> 送金確認画面に遷移
以上のように変更します
