### ISSUE TITLE
トランザクション詳細でアドレスをコピーできない

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#20]
わーい！寄付もらったぞ！
↓
メッセージでお礼するンゴ。
↓
トランザクション詳細でコピーできない！

**Comment by SasakiYuki** [comment]
個人的にはトランザクション詳細でアドレスを押したときにやりたいこと
xembookさんに飛ぶ or xembookさん相当の相手のアドレス情報を表示する画面を作る(アドレス帳へ追加などのアクションにもつながる）
みたいなことがしたい
アドレスのコピーはアドレスそのものをタップよりもアイコンをおいてそれをタップするとコピーできる　みたいな感じを想定してますがデザイン的に言うとどうですか？

**Comment by Rhime-design** [comment]
おお、相手のアドレス活動覗いてチェックすべき情報ってなんかありますかね？

確かにアドレスタップから、下からにゅっとなんか出てきて「アドレス帳に登録する」「アドレスをコピー」とかで繋げて行くのは良い感じだとおもう！

**Comment by Rhime-design** [comment]
![2018-07-01_03h34_28](https://user-images.githubusercontent.com/34479640/42128147-ab9af33e-7cdf-11e8-93f0-696243d3bd59.png)

とりま、緑のテキストを押すと単純にコピーできるようにしていただきたく…
