### ISSUE TITLE
ウォレット管理画面での移動アニメーションのFix

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#21]
ウォレットボタンを押して、上から来るぞ気をつけろ！、で降ってきたウォレット管理画面のリストからウォレットごとの設定（歯車）を押した場合、移動は右から左（←⦿）でお願いします。

要するに、ウォレット管理が降ってきたあとは、← →　のページ移動でお願いします。

**Comment by SasakiYuki** [comment]
あざます！やります！

**Comment by Rhime-design** [comment]
これ、まだ治ってないですｗ
自力でやれれば良いんですが…お願いします
