### ISSUE TITLE
アドレス入力時にボタンからテキストをペーストできると良い

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#22]
テキストフィールドの右側にアイコン：icon_clipboard.png　を表示させて、クリップボードにコピーしたテキスト（アドレス）を一発で入力できると素敵。

Asset：
https://github.com/SasakiYuki/RaccoonWallet/blob/master/app/src/main/res/mipmap-xxxhdpi/icon_clipboard.png

**Comment by SasakiYuki** [comment]
ペーストは長押しでできるのでできるのでそこまで重要性を感じない？

コピーアイコンは見たことあるけどあんまりペーストアイコンってあんまり見ないかもなぁ？とか思いつつそうでもないのかなとも

**Comment by Rhime-design** [comment]
https://github.com/SasakiYuki/RaccoonWallet/blob/master/app/src/main/res/mipmap-xxxhdpi/icon_close_circle.png

確かに、あんまり見ないですよね！

あってもなくてもぐらいかなあ。

ただ、テキストを一発削除できるバッテンは欲しいかもしれないです。

**Comment by SasakiYuki** [comment]
バッテンは実装しましょう！！！ありがとうございます！！

**Comment by Soma-Kato** [comment]
テキストフィールドに何も入っていないときは「ペーストボタン」、1文字でも入っていたら「削除ボタン」に出し分けたらどうでしょうか？

**Comment by Rhime-design** [comment]
理想的な実装です！
ありがたき！
