### ISSUE TITLE
App is not able to import 66 length private key

### ISSUE THREAD

**Issue by cryptoBeliever** [SasakiYuki/RaccoonWallet#25]
Official NEM Android (probably also IOS) app could create private key as 66 signs with leading 00.
It's not possible to import such private key in RaccoonWallet.

![qr_share](https://user-images.githubusercontent.com/17684281/41195754-d5824c22-6c33-11e8-9164-e9963249cfde.png)

Password: testing
Private key: 009db3d7b243a368e982ce9de95ab9ef716a212d8856bba96f5512bc7cf5d88e1f

When I try import it into Raccoon wallet I have error. Putting directly private key as text also don't work.

**Comment by Soma-Kato** [comment]
Thanks for reporting 🙇
Closing the issue as the fix is merged.
