### ISSUE TITLE
Mini transfers view on dashbord show transfers don't refresh

### ISSUE THREAD

**Issue by cryptoBeliever** [SasakiYuki/RaccoonWallet#29]
When I change wallet mini transfers view on dashbord don't reload.
Both screenshots showed transfers for wallet named "w2".

![screenshot_2018-06-09-22-48-53-996_wacode yamada yuki nempaymentapp](https://user-images.githubusercontent.com/17684281/41196009-264917fe-6c38-11e8-83be-e336c22ef16b.png)

![screenshot_2018-06-09-22-49-09-418_wacode yamada yuki nempaymentapp](https://user-images.githubusercontent.com/17684281/41196012-28aa6516-6c38-11e8-811a-633501297a59.png)

**Comment by Rhime-design** [comment]
Since home screen refresh with up swipe has been implemented, close the issue.:raised_hands:
