### ISSUE TITLE
タブレット最適化

### ISSUE THREAD

**Issue by SasakiYuki** [SasakiYuki/RaccoonWallet#3]
## まずは既存でヤバいところを直す

修正予定物

- [ ]   HOMEのタブ
- [ ]   DIALOG
- [ ]   ヒーローイメージ

## どう修正すればいいのかわからないもの

ウォレット作成選択画面のカードは幅いっぱい？

**Comment by Rhime-design** [comment]
１．レイアウトの崩れを直す程度
２．タブレットならではのレイアウトを新たに作成

の２つを考慮しつつ進める。
かつ、回転考慮で生ずるクラッシュをシンプルに解決するため、タブレットは横画面オンリーにする。

![2018-05-29_19h09_20](https://user-images.githubusercontent.com/34479640/40712666-3190ff20-6439-11e8-98b2-edd6f252248b.png)
タブレットならではのレイアウト例

<br><br>
（プライベートリポジトリからの移植）
タブレットでのテストをしてみました。

テスト環境が、GooglePlayを使えるようにごにょったkindle fire 7という不安なヤツではありますが、ストアからインストールしたRaccoonWallet を起動したところレイアウト崩れを確認しました。
できればちゃんとしたタブレットでも同様の崩れが起きているか確認しておきたいところです。

## スクリーンショット

<br>

![screenshot_2018-05-21-23-37-48](https://user-images.githubusercontent.com/34479640/40340192-b852cb1a-5db8-11e8-84d0-196e6fbc0ecf.png)
![screenshot_2018-05-21-23-38-01](https://user-images.githubusercontent.com/34479640/40340193-b88eaef0-5db8-11e8-876f-c4cd513feeac.png)
![screenshot_2018-05-21-23-38-39](https://user-images.githubusercontent.com/34479640/40340194-b8c9aa32-5db8-11e8-9748-42949a32edf8.png)
![screenshot_2018-05-21-23-38-09](https://user-images.githubusercontent.com/34479640/40340195-b9054e3e-5db8-11e8-9417-c6263c18acf3.png)

**Comment by Rhime-design** [comment]
今すべての画面が横になって大丈夫なのか？
について検討しています。

なんか雰囲気的に大丈夫っぽそうですけど、想定外の制限で縦がでる可能性も否定できない…かな？
とはいえデザインを変えれば収められないものもないし、すべて横でもよさそうな気がします。
横なら横としたほうが、操作するたび、たまにぐるぐるしてよう分からんことにならないし。

![2018-06-02_00h50_59](https://user-images.githubusercontent.com/34479640/40850242-1a677f82-65ff-11e8-95df-0a2284e3eaa0.png)

androidタブレットの解像度がXDによると、1024×768らしいですがこれで大丈夫でしょうか？

この比率でよいのなら、基本的にスマートフォンレイアウトの要素は基本的に２倍になる感じのようです。
例えばHeroimage_smallはw720 h200になります。（ただHeroimage_largeはでかすぎるのですべてsmallに置き換えることもありそう。）


![2018-06-02_01h09_26](https://user-images.githubusercontent.com/34479640/40851212-97cc70f2-6601-11e8-99c2-22fdf82a8526.png)

HOMEはこんなふうになったらきれいかも？

ボトムナビ修正してくれいとか適当に言ってしまい申し訳ないですが、ちょっち待ってください。

**Comment by SasakiYuki** [comment]
http://tokidoki-web.com/2013/01/%E3%80%8E%E3%82%B9%E3%83%9E%E3%83%9B%E3%83%BB%E3%82%BF%E3%83%96%E3%83%AC%E3%83%83%E3%83%88%E3%81%AE%E3%82%B5%E3%82%A4%E3%82%BA%E8%A7%A3%E5%83%8F%E5%BA%A6%E4%B8%80%E8%A6%A7%E4%BD%9C%E3%81%A3%E3%81%A6/
よくわからなくなってきた

**Comment by SasakiYuki** [comment]
> 横なら横としたほうが、操作するたび、たまにぐるぐるしてよう分からんことにならないし。
そう思います！
労力を払う価値があると僕は思ってます！（タブレット完全対応

**Comment by Rhime-design** [comment]
Googleがタブレット撤退？ｗ
https://twitter.com/CryptoRhizome/status/1002838488348123139
↓
しかしRaccoonを紹介しもらった記事
https://xn--gdk3b3a2ex03r2uw267du0f.com/%E3%82%A6%E3%82%A9%E3%83%AC%E3%83%83%E3%83%88%E4%BB%AE%E6%83%B3%E9%80%9A%E8%B2%A8/
スクショみるかぎりタブレットを使用されているか。
レイアウトが崩れるのは許しがたい…（憤タヌ
↓
でもタブレットよく分からん。

そしてタブレット＆POSとなると、かなり大規模（個人的な印象では。
果たしてワシは無料のまま突き進めるのか…
PRO版とか…

一度アンケートを取ってみても、、、？

![2018-06-02_19h36_52](https://user-images.githubusercontent.com/34479640/40873514-50aea6b8-669c-11e8-9d9c-78772d3191b6.png)

**Comment by SasakiYuki** [comment]
アンケートぜひとってみましょう！
なんかそこまで需要ないなら気分上がんないですし笑
無料でやるかどうか、よりも「そんなんいらねーよ」と思われてるかどうかをまず知りたい。
そのうえで「ぜひプロ版にもしたいと思う！」と思ってくれるならより嬉しいし。
お願いしちゃっていいですかね？一番影響力あるし笑

MediaPadわしも欲しい。
5:8ワロタ　くそ比率

**Comment by SasakiYuki** [comment]
16:9か16:10　あたりすかね。。。

**Comment by Rhime-design** [comment]
iPhone X　2:1ですよ？？？？
4sまでの3:2がやっと死んだとiOSディベロッパーが歓喜してた気がしますが、なんなんだ！？！？！？！

**Comment by SasakiYuki** [comment]
ｗｗｗｗｗ
2:1ｗｗｗｗｗｗ

UIデザイナーを殺す機械

**Comment by Rhime-design** [comment]
:innocent::innocent::innocent:

**Comment by SasakiYuki** [comment]
まぁメインのやつだけ決めていただければこちらでタブレットの近いやつは相談しつつ調整しますよ！

**Comment by SasakiYuki** [comment]
７と９じゃどっちにしろレイアウトは２つ用意しないとダメそうだし。。

**Comment by Rhime-design** [comment]
１０分しか経ってませんが（せっかち）、面白いぐあいです。
![2018-06-02_22h56_11](https://user-images.githubusercontent.com/34479640/40877232-32d6972e-66b8-11e8-92e8-13fdbb579042.png)

**Comment by SasakiYuki** [comment]
端的にいって金になる 💰

**Comment by SasakiYuki** [comment]
そしてモチベになる

**Comment by SasakiYuki** [comment]
というかみんなすげー早く答えてくれる！！ありがてぇ。。

**Comment by Rhime-design** [comment]
やっぱPOSシステムとして切り離したものをリリースしてもよいのでは？という意見も。（しおじいさんから。
でもなんかあっちこっちでイメージが分散するからまとめてやりたいというのもある、、、、

**Comment by SasakiYuki** [comment]
そうですね。僕もRaccoonのブランドをもりっとまとめられるのは同じアプリ内のほうがいいのかなとも思いつつ、、でも実装的にどっちがいいのか、とか思うとそれもまた難しいかいやでも１から大変か。。とか

そうしましょう笑
一旦まとめますね

アンケート結果より
- タブレットデザインを導入することで一定の支持が得られそう
- タブレットによる簡単なPOSシステムは購入してでも使ってくれる人が多い
- 値段及び支払方法は検討
- Android/iOS比率は 42:52:その他　

https://twitter.com/CryptoRhizome/status/1002906797789700097

検討事項
- 別アプリとして切り離すか
- 横画面どこまでサポートするか問題
- タブレットの解像度（もうすでにRhimeさんの中では決着ついてる？）

**Comment by SasakiYuki** [comment]
一定期間動いていないためリポジトリールールによりクローズします🤖
議論が必要になった際に再オープンしましょう🤖
