### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by chpecson** [SasakiYuki/RaccoonWallet#31]
UX/UI is awesome and will be great to support many languages such as English, etc. to let the worldwide users understand the app. Thanks.

**Comment by SasakiYuki** [comment]
First 
https://medium.com/raccoonwallet/raccoon%E3%81%AE%E5%A4%9A%E8%A8%80%E8%AA%9E%E5%8C%96%E3%81%AB%E5%90%91%E3%81%91%E3%81%9F%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%85%AC%E9%96%8B%E3%81%A8%E5%8F%82%E5%8A%A0%E3%81%AE%E3%81%8A%E9%A1%98%E3%81%84-af297047cd08

JP -> EN 
using Transifex

After that it is undecided so far so far but everyone wants to do it
