### ISSUE TITLE
先頭が00で始まる秘密鍵について(About secret key whose head begins with 00)

### ISSUE THREAD

**Issue by mizunashi** [SasakiYuki/RaccoonWallet#34]
現在は、00で始まる秘密鍵を使ったウォレットを作成する場合、00を外さないとエラーになります。
単純に今まで公式ウォレットを使っていた人には、それを知ってもらう必要があります。
どちらかといえば、アプリケーション側で解決した方が良いと考えます。
<hr/>
Currently, if you create a wallet with a secret key that starts with 00, you will get an error unless you remove 00.
People who used the official wallet until now simply need to know about it.
If anything, I think that it is better for the application to solve it.

**Comment by SasakiYuki** [comment]
ありがとうございます！
そういうことだったんですね。アプリ側で対応したほうがユーザーフレンドリーに思えるので対応したいと思います！！！

**Comment by SasakiYuki** [comment]
英語
Do it right now!
