### ISSUE TITLE
アプリ評価の催促ダイアログ

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#5]
ウザくない程度に、アプリ評価の催促ダイアログを出してもらえるとユーザーにとって参考になる情報が増える流れができて良いかな、と思いました。

コンポーネントは、普通の汎用ダイアログで良いと思われ。

**Comment by SasakiYuki** [comment]
やりましょう
タヌキダイアログでもいいかな、と思ったけどなんかちょっとうるさく感じちゃうかそれだと

3日に一回くらい？やりすぎ？

文言は先生みたいなフランクな感じでいいかな？
「毎度！RaccoonWalletを利用してくれてありがとう！もしよかったらレビューを書いてくれないかい？」
普通のやつ
「いつもご利用ありがとうございます。もしよろしければレビューをお願いします。」

**Comment by Rhime-design** [comment]
![2018-06-01_19h19_33](https://user-images.githubusercontent.com/34479640/40836161-b9a4dcf4-65d0-11e8-9557-26d6dfb0cf34.png)

`RaccoonWalletを利用してくれてありがとう。
突然だけど、もしよかったらレビューを書いてはくれないかい？
書いてくれたら君には特別に、ラクーンエヴァンジェリスト・ライセンスを授与しよう。
…なにかよこせ？ライセンスはあなたの心の中にあります。`

<br>

一度きりで良い気がします。
ダイアログはタヌキでいいんじゃないかなあ。
ダイアログ出現は、初起動から三日後ぐらいでしょうか？？？

それ以降は、「タヌキの外部リンクがあるのはここかな？」と予測できるので、Aboutの部分から「レビューを書く」を設けて、
`レビューを書く`→`催促ダイアログ（せっかくなのでストアへ直接移動せず、初回時のダイアログを出す）`→`ストアへ移動`

という感じでしょうか？

**Comment by Rhime-design** [comment]
再表示しない　で閉じたあとも継続して催促ダイアログが表示されてしまうのを確認しました。
チェックを入れて閉じた後は、再インストールとかしない限り表示させない感じでよろしくです( ｀・∀・´)ﾉ
