### ISSUE TITLE
iOSデザインチェックリスト

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#79]
▼UI/UX

- [ ] Android版みたいにHOMEをスワイプでｼｭｯｼｭｯっと移動したい。
- [ ] 左端→→スワイプでドロワーを出したい。

- [ ] トランザクション画面でのスクロール時に、heroimageが隠れない
- [ ] Android版もですが、Hello NEMber、やっぱ別に要らないかな…いや…どうなんだろう
- [ ] Android版もですが、ウォレットバーのウォレットボタンのタップ反応範囲がシビアなので、ボタンより一回り大きくしたい。
- [ ] アドレスコピー（他）のトーストがボトムナビに被るのをどうにかしたい👀
ボトムナビはドロワーを除けば最上位Layerに位置していて、他の要素侵食されないでほしい。

- [ ] HOMEの残高やトランザクションの小窓が表示のつどローディングされるのを、初回で取得した後、キャッシュとか（？）を使ってイベント時やユーザーの下スワイプが入力されたとき以外は静的に表示しておいてほしい。
- [ ] ローディングが要素ごとに表示される部分に関して。
↑に書いた挙動を前提にしていますが、
iOS標準（たぶん）のちっこいローディングを、オーバーレイで画面中央に表示する程度で良いと思いました。
![2018-09-27_09h39_28](https://user-images.githubusercontent.com/34479640/46116896-3ef57c00-c239-11e8-9044-6b29ac30fa98.png)

- [ ] 送金確定時にPINを使う際のボタンがない。

▼不具合・改善

- [ ] 指紋認証で送金できない？
- [ ] Tx取得やQR読み込み、SEND完了などのローディングがちょっと遅い？

まだざっくりなんで、随時追記します。

**Comment by SasakiYuki** [comment]
> Android版もですが、Hello NEMber、やっぱ別に要らないかな…いや…どうなんだろう
何にします？消しちゃうだけだと寂しい？そんなことない？
と思って色々見てみたけどTopのToolbarって結構みんな持て余してますね　ハンバーガー（うちでいうNEMボタン）とかは置いてあるけどテキストスペースはみんな微妙な感じ

Spotifyも HOME とだけ　いらない情報
YoutubeもロゴとYoutube 
Twitter ホーム
Kayash ウォレット
Amazon ロゴのみ

**Comment by Rhime-design** [comment]
んー、なんというか内輪な感じがして。コミュニティ感があるといえばそれはそれで良いのですが。
スカスカになる点に関しては、今後マルチシグ通知とかでベルマークとか置いたりも可能性としてあるので、まあいいかなという。

**Comment by SasakiYuki** [comment]
なるほど。そしたら無難にRaccoonWallet とかにしちゃったほうがいいか。
Rhimeさんの納得いく感じに調整してもらって問題ないですが大きくいじるのは通知とか回りの実装をしたときですかね（トランザクション通知　ハーベスト通知　マルチシグ　等）
ベル置いたらNEMマークも移動しそうだし

**Comment by Rhime-design** [comment]
やっぱツールは右で、ドロワーは左ですかね？
なんか世間と感覚が逆？ｗ右のほうが自然な気がするんですが、よく分からぬ。

←🔔 　[真ん中：ロゴ]　⭐️ドロワー

みたいなのでもいいかなとか。
そのあたりは時がきたらデザインのほうで置いて確認してみます。

**Comment by SasakiYuki** [comment]
基本的にはそうかと思います笑
あくまで私のは根拠のない一般的なアプリにおいてはそう、という視点なのでアレですが。

_____________________________
🍔 RaccoonWallet      　🔔　
￣￣￣￣￣￣￣￣￣￣￣￣
みたいなののほうがよく見る感じではあります。

そうですね！通知も一応ブランチはあるっちゃあるのでまた近くなってきたら相談します！

**Comment by Rhime-design** [comment]
iOSリポジトリinviteしてもらったので、やり取りはあちらでやることにしますね！
