### ISSUE TITLE
[Android]フレンドリスト：デザインチェックリスト

### ISSUE THREAD

**Issue by Rhime-design** [SasakiYuki/RaccoonWallet#80]
- [x] huaweiボタン「選択」「追加」などが2つ以上並んでいるときのスペースが狭く誤動作を誘発する→スペースを開けて誤操作をなくしたい。
![2018-09-27_09h57_08](https://user-images.githubusercontent.com/34479640/46117366-dbb91900-c23b-11e8-8995-3c45c9591eef.png)

- [x] ドロワーメニューのアイコン横の情報は、シンプルに名前だけにしたほうがいいかと思ってきました。（↓に貼った画像で確認
- [x] ドロワーメニューのユーザー指定背景画像に**白色の領域が多い画像が設定された時**、**テキストの可読性がなくなる。**
→**背景画像のすぐ上に↓から↑にかけて不透明度56%→0になる#000000のグラデーション）**を配置**して、テキストとのコントラストを確保する。
![img_20180926_112958](https://user-images.githubusercontent.com/34479640/46117374-e5db1780-c23b-11e8-8024-332a27c268d4.jpg)

![2018-09-27_10h35_30](https://user-images.githubusercontent.com/34479640/46118442-7ec06180-c241-11e8-9069-6b35477c4131.png)
`グラデーション適用後。可読性が保たれている。`

![2018-09-27_10h37_48](https://user-images.githubusercontent.com/34479640/46118471-a44d6b00-c241-11e8-8c44-dacd3fecd2be.png)

- [x] ウォレット追加時に画面に反映されない。追加完了時に自動リフレッシュがほしい
- [ ] アドレスのタップ時のコピー。あとメルアドなどの諸情報もタップコピーがあると良い
- [x] 一覧から入った個人ページでの名前とふりがなを左揃え→中央揃えにしたい
![2018-09-27_09h58_54](https://user-images.githubusercontent.com/34479640/46117409-1327c580-c23c-11e8-92f9-6a6166967a97.png)

- [x] フレンドリスト個人ページの名前下タブの「ウォレット」の右側が「連絡先」と「プロフィール」でバラバラなので「**プロフィール**」に統一したい。
![2018-09-27_10h08_48](https://user-images.githubusercontent.com/34479640/46117651-5f273a00-c23d-11e8-9bb0-0948eef6d439.png)
![2018-09-27_10h08_56](https://user-images.githubusercontent.com/34479640/46117652-5f273a00-c23d-11e8-83ef-19259d5c6415.png)

- [x]  フレンドを新規登録する際に、最初に飛ぶタブを「ウォレット」から「プロフィール」に変更したい。（理由：心理的に「ウォレット登録より先に、これは誰のリストなのか？」を設定したいため。
ただし、登録し終わったあとは、先にアクセスしたいのはウォレット情報なので、タブの並びはこのままで良い。

![2018-09-27_10h02_39](https://user-images.githubusercontent.com/34479640/46117656-69e1cf00-c23d-11e8-8cea-d8a1529d8147.png)

- [x] フレンドを新規登録する際に、 **プロフィールを必須**、**ウォレット登録を任意**にしたい。
（理由：フレンドだけを登録して、ウォレットはemptyの状態にしたい場合もある。逆に、その反対の作業は多分まれ。

🔔2018,10/1追記

![2018-10-01_14h41_13](https://user-images.githubusercontent.com/34479640/46271641-7b521080-c588-11e8-9864-4f08f6db8046.png)
- [x] 非アクティブでないテキストフィールドはグレーになっていてほしい。

<br><br>
随時追記🖋

**Comment by SasakiYuki** [comment]
huaweiボタン「選択」「追加」などが2つ以上並んでいるときのスペースが狭く誤動作を誘発する→スペースを開けて誤操作をなくしたい。
2018-09-27_09h57_08

  ドロワーメニューのアイコン横の情報は、シンプルに名前だけにしたほうがいいかと思ってきました。（↓に貼った画像で確認

  ドロワーメニューのユーザー指定背景画像に白色の領域が多い画像が設定された時、テキストの可読性がなくなる。
→**背景画像のすぐ上に↓から↑にかけて不透明度56%→0になる#000000のグラデーション）を配置して、テキストとのコントラストを確保する。
img_20180926_112958

2018-09-27_10h35_30
グラデーション適用後。可読性が保たれている。

2018-09-27_10h37_48

  ウォレット追加時に画面に反映されない。追加完了時に自動リフレッシュがほしい

  アドレスのタップ時のコピー。あとメルアドなどの諸情報もタップコピーがあると良い

  一覧から入った個人ページでの名前とふりがなを左揃え→中央揃えにしたい
2018-09-27_09h58_54

  フレンドリスト個人ページの名前下タブの「ウォレット」の右側が「連絡先」と「プロフィール」でバラバラなので「プロフィール」に統一したい。
2018-09-27_10h08_48
2018-09-27_10h08_56

  フレンドを新規登録する際に、最初に飛ぶタブを「ウォレット」から「プロフィール」に変更したい。（理由：心理的に「ウォレット登録より先に、これは誰のリストなのか？」を設定したいため。
ただし、登録し終わったあとは、先にアクセスしたいのはウォレット情報なので、タブの並びはこのままで良い。

2018-09-27_10h02_39

  フレンドを新規登録する際に、 プロフィールを必須、ウォレット登録を任意にしたい。
（理由：フレンドだけを登録して、ウォレットはemptyの状態にしたい場合もある。逆に、その反対の作業は多分まれ。
🔔2018,10/1追記

2018-10-01_14h41_13

  非アクティブでないテキストフィールドはグレーになっていてほしい。
