### ISSUE TITLE
要望：フレンドリストのプロフィール欄に宛先タグを登録したい

### ISSUE THREAD

**Issue by mediaprogramer** [SasakiYuki/RaccoonWallet#99]
xemの取引所やtipnemに送金する場合、payload部に入金用メッセージの入力が必要になります。
この部分の文字列を探しに行くのが毎回面倒なため、フレンドリストのプロフィール欄に保存できれば便利だと思います。

希望する動作としては、
1.フレンドリストのプロフィールに入金用メッセージを事前に登録しておく。
2.送金を行う、宛先を選択し、金額を確定して「→」ボタンをタップ
3.「メッセージを添付しますか？」の画面を経由せず、メッセージ欄に入金用メッセージが埋め込まれた状態で「送金の最終確認画面です」に到達
4,PIN認証で送金完了

といった流れです。
ご検討よろしくお願いします。

**Comment by SasakiYuki** [comment]
入金用のタグって毎回変わるものじゃないんですね　知らなかったです 👀 
ちょっとセルフGOXの機会を増やしてしまいそうじゃないかな...?と危惧しています。

**Comment by mediaprogramer** [comment]
たしかにセルフGOXの危険性は出てきますね。バグがあるとまずい部分なのでそれ用とは言わずに定型文（フッター）挿入機能みたいな感じでどうでしょうか？w

**Comment by SasakiYuki** [comment]
https://github.com/SasakiYuki/RaccoonWallet/issues/103
自由入力を設けて完了、というわけにもいかなそうなのでちょっと別のアプローチを考えています。
